# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receive_Google_Data',
        ),
        migrations.DeleteModel(
            name='Receive_Naver_Data',
        ),
    ]
